rabbitmq1:
  image: "rabbitmq:3-management"
  hostname: "rabbitmq1"
  ports:
    - "1001:15672"
    - "1011:5672"
    - "1883:1883"
  labels:
    NAME: "rabbitmq1"
  restart: always

rabbitmq2:
  image: "rabbitmq:3-management"
  hostname: "rabbitmq2"
  ports:
    - "1002:15672"
    - "1012:5672"
    - "1884:1883"
  labels:
    NAME: "rabbitmq2"
  restart: always

rabbitmq3:
  image: "rabbitmq:3-management"
  hostname: "rabbitmq3"
  ports:
    - "1003:15672"
    - "1013:5672"
    - "1885:1883"
  labels:
    NAME: "rabbitmq3"
  restart: always